apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.backend.name }}-config
  namespace: {{ .Values.namespaces.app }}
data:
  PORT: {{ .Values.backend.port | quote }}
  NODE_ENV: {{ .Values.backend.env.NODE_ENV | quote }}
  MONGO_HOST: {{ include "mongodb.dns" . | quote }}
  MONGO_PORT: {{ .Values.mongodb.port | quote }}
  MONGO_DB: {{ .Values.mongodb.auth.database | quote }}
