apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Values.namespaces.app }}
  labels:
    app: {{ .Values.backend.name }}
    {{- include "k8sbase.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}
    spec:
      containers:
        - name: {{ .Values.backend.name }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          envFrom:
            - configMapRef:
                name: {{ .Values.backend.name }}-config
            - secretRef:
                name: {{ .Values.backend.name }}-secret
          resources:
            requests:
              memory: {{ .Values.backend.resources.requests.memory | quote }}
              cpu: {{ .Values.backend.resources.requests.cpu | quote }}
            limits:
              memory: {{ .Values.backend.resources.limits.memory | quote }}
              cpu: {{ .Values.backend.resources.limits.cpu | quote }}
          livenessProbe:
            httpGet:
              path: {{ .Values.backend.probes.path }}
              port: {{ .Values.backend.port }}
            initialDelaySeconds: {{ .Values.backend.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.probes.liveness.periodSeconds }}
            failureThreshold: {{ .Values.backend.probes.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.backend.probes.path }}
              port: {{ .Values.backend.port }}
            initialDelaySeconds: {{ .Values.backend.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.probes.readiness.periodSeconds }}
            failureThreshold: {{ .Values.backend.probes.readiness.failureThreshold }}
